// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUcELA0pyOWZXS29AP1z8MpD5zBDuovPk',
    appId: '1:450406837124:web:a8c593d8ffb1faf2e14bd1',
    messagingSenderId: '450406837124',
    projectId: 'hands-talk-b9864',
    authDomain: 'hands-talk-b9864.firebaseapp.com',
    storageBucket: 'hands-talk-b9864.firebasestorage.app',
    measurementId: 'G-5HLQPWJBXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHtT0SCST_Ui65eI7umSCtV4ky2JhMqs',
    appId: '1:450406837124:android:05a8d28b2dbd965de14bd1',
    messagingSenderId: '450406837124',
    projectId: 'hands-talk-b9864',
    storageBucket: 'hands-talk-b9864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCstEjabkraEsGOZT6usJf6wQGbnUEDg0U',
    appId: '1:450406837124:ios:ef036434dfbe7176e14bd1',
    messagingSenderId: '450406837124',
    projectId: 'hands-talk-b9864',
    storageBucket: 'hands-talk-b9864.firebasestorage.app',
    iosBundleId: 'com.example.handsTalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCstEjabkraEsGOZT6usJf6wQGbnUEDg0U',
    appId: '1:450406837124:ios:ef036434dfbe7176e14bd1',
    messagingSenderId: '450406837124',
    projectId: 'hands-talk-b9864',
    storageBucket: 'hands-talk-b9864.firebasestorage.app',
    iosBundleId: 'com.example.handsTalks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUcELA0pyOWZXS29AP1z8MpD5zBDuovPk',
    appId: '1:450406837124:web:fcacb7bfc664fa21e14bd1',
    messagingSenderId: '450406837124',
    projectId: 'hands-talk-b9864',
    authDomain: 'hands-talk-b9864.firebaseapp.com',
    storageBucket: 'hands-talk-b9864.firebasestorage.app',
    measurementId: 'G-WX14TDYCF6',
  );
}
