// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_MbAqXBHIyhw1miU0-VM0iObkkxGhFHQ',
    appId: '1:9803608938:web:307099d10e74e76777eb13',
    messagingSenderId: '9803608938',
    projectId: 'hands-talks-e581c',
    authDomain: 'hands-talks-e581c.firebaseapp.com',
    storageBucket: 'hands-talks-e581c.firebasestorage.app',
    measurementId: 'G-XJJPFKZYNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBMPLkopCwYjRf-preAgj5_OH4OZiiaJw',
    appId: '1:9803608938:android:8afc88497ea6865977eb13',
    messagingSenderId: '9803608938',
    projectId: 'hands-talks-e581c',
    storageBucket: 'hands-talks-e581c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1W4i5_6JaodlKJ9-RuxCBrwrHbdesDXM',
    appId: '1:9803608938:ios:260f5e354648295977eb13',
    messagingSenderId: '9803608938',
    projectId: 'hands-talks-e581c',
    storageBucket: 'hands-talks-e581c.firebasestorage.app',
    iosBundleId: 'com.example.handsTalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1W4i5_6JaodlKJ9-RuxCBrwrHbdesDXM',
    appId: '1:9803608938:ios:260f5e354648295977eb13',
    messagingSenderId: '9803608938',
    projectId: 'hands-talks-e581c',
    storageBucket: 'hands-talks-e581c.firebasestorage.app',
    iosBundleId: 'com.example.handsTalks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_MbAqXBHIyhw1miU0-VM0iObkkxGhFHQ',
    appId: '1:9803608938:web:627ceffca48c4a9c77eb13',
    messagingSenderId: '9803608938',
    projectId: 'hands-talks-e581c',
    authDomain: 'hands-talks-e581c.firebaseapp.com',
    storageBucket: 'hands-talks-e581c.firebasestorage.app',
    measurementId: 'G-Q25MQZVJJF',
  );
}
